# Generated by Django 4.0.4 on 2022-06-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googletoken',
            name='code',
        ),
        migrations.RemoveField(
            model_name='googletoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='googletoken',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='googletoken',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='googletoken',
            name='token_type',
        ),
        migrations.RemoveField(
            model_name='googletoken',
            name='user',
        ),
    ]
