# Generated by Django 4.0.4 on 2022-06-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0003_googledata_delete_googletoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledata',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
