# Generated by Django 4.0.4 on 2022-06-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0004_alter_googledata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledata',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='googledata',
            name='user',
            field=models.CharField(max_length=400),
        ),
    ]
