# Generated by Django 4.0.4 on 2022-06-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_classifieds_deals_events_product_multiplelocations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.CharField(max_length=40),
        ),
    ]
