# Generated by Django 4.0.4 on 2022-06-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_business_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='timingfrom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='business',
            name='timingto',
            field=models.CharField(max_length=120),
        ),
    ]
