# Generated by Django 4.0.4 on 2022-06-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_business_timingfrom_alter_business_timingto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/business/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
    ]
