# Generated by Django 4.0.4 on 2022-06-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_business_image_field_alter_product_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='hello this is description', max_length=200),
        ),
    ]
