# Generated by Django 4.0.4 on 2022-06-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='website_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
