# Generated by Django 4.0.4 on 2022-06-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_business_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifieds',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='image_field',
            field=models.ImageField(blank=True, default='images/business/hasab.jpg', null=True, upload_to='images/business/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_field',
            field=models.ImageField(blank=True, default='images/products/hasab.jpg', null=True, upload_to='images/products/'),
        ),
    ]
