# Generated by Django 4.0.4 on 2022-06-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_classifieds_slug_deals_slug_events_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifieds',
            name='image_field',
            field=models.ImageField(blank=True, default='images/products/hasab.jpg', null=True, upload_to='images/classifieds/'),
        ),
        migrations.AlterField(
            model_name='deals',
            name='image_field',
            field=models.ImageField(blank=True, default='images/products/hasab.jpg', null=True, upload_to='images/deals/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image_field',
            field=models.ImageField(blank=True, default='images/products/hasab.jpg', null=True, upload_to='images/events/'),
        ),
    ]
