# Generated by Django 4.0.4 on 2022-06-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_classifieds_image_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifiedsrating',
            old_name='business',
            new_name='classifieds',
        ),
        migrations.RenameField(
            model_name='dealsrating',
            old_name='business',
            new_name='deals',
        ),
        migrations.RenameField(
            model_name='eventsrating',
            old_name='business',
            new_name='events',
        ),
    ]
