# Generated by Django 4.0.4 on 2022-06-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_business_classifiedsrating_classifieds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='datefrom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deals',
            name='dateto',
            field=models.CharField(max_length=20),
        ),
    ]
