# Generated by Django 4.0.4 on 2022-06-14 08:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='agasdgas', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='asasgd', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=0, max_length=128, region=None),
        ),
    ]
