# Generated by Django 4.0.4 on 2022-06-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_profile_location_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_field',
            field=models.ImageField(blank=True, default='images/profile/avatar.png', null=True, upload_to='images/profile/'),
        ),
    ]
