# Generated by Django 4.0.4 on 2022-06-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_business_rate_classifieds_rate_deals_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='classifieds',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='events',
            name='rate',
        ),
    ]
