# Generated by Django 4.0.4 on 2022-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_business_rate_classifieds_rate_deals_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classifieds',
            name='rate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deals',
            name='rate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='rate_count',
            field=models.IntegerField(default=0),
        ),
    ]
