# Generated by Django 4.0.4 on 2022-06-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
