# Generated by Django 4.0.4 on 2022-06-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_product_created_at_profile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='map_link',
        ),
    ]
