# Generated by Django 4.0.4 on 2022-06-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_remove_business_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='approve_reviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classifieds',
            name='approve_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deals',
            name='approve_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='approve_review',
            field=models.BooleanField(default=False),
        ),
    ]
