# Generated by Django 4.0.4 on 2022-06-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_business_approve_reviews_classifieds_approve_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifieds',
            old_name='approve_review',
            new_name='approve_reviews',
        ),
        migrations.RenameField(
            model_name='deals',
            old_name='approve_review',
            new_name='approve_reviews',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='approve_review',
            new_name='approve_reviews',
        ),
    ]
