# Generated by Django 4.0.4 on 2022-06-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_remove_multiplelocations_map_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplelocations',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
