# Generated by Django 4.0.4 on 2022-06-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_multiplelocations_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplelocations',
            name='timingfrom',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='multiplelocations',
            name='timingto',
            field=models.CharField(max_length=9),
        ),
    ]
