# Generated by Django 4.0.4 on 2022-06-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_business_email_alter_business_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrating',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classifiedsrating',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealsrating',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventsrating',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
