# Generated by Django 4.0.4 on 2022-06-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='item_slug',
            field=models.SlugField(default='default', max_length=100, unique=True),
        ),
    ]
