# Generated by Django 4.0.4 on 2022-06-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_remove_favourites_image_field_favourites_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='image_url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='item_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='item_title',
            field=models.CharField(max_length=100),
        ),
    ]
